#!/usr/bin/env bash
set -e

name=libxcvt
ver=0.1.3
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libxcvt-0.1.3.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

