#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxinerama
ver=1.1.5
dependencies=(
libxcb
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXinerama-1.1.5.tar.xz
prefix=/var/xor/prefixes/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

