#!/usr/bin/env bash
set -e

name=libxinerama
ver=1.1.5
dependencies=(
libxcb
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXinerama-1.1.5.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

