#!/usr/bin/env bash
set -e

name=fribidi
ver=1.0.16
dependencies=()

make_dependencies=""
url=https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

