#!/usr/bin/env bash
set -e

name=libtirpc
ver=1.3.6
dependencies=()

make_dependencies=""
url=https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.6.tar.bz2

configure() {
	sudo ./configure --prefix=/usr --sysconfdir=/etc --disable-static --disable-gssapi
	sudo make
}

build() {
	sudo make install
}

