#!/usr/bin/env bash
set -e

name=libxtst
ver=1.2.5
dependencies=(
	libxi
	)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXtst-1.2.5.tar.xz

configure() {
	sudo ./configure --prefix=/usr
	sudo make
}

build() {
	sudo make install
}

