#!/usr/bin/env bash
set -e

name=libxt
ver=1.3.1
dependencies=(
libice
libsm
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXt-1.3.1.tar.xz

configure() {
	sudo ./configure --prefix=/usr --with-appdefaultdir=/etc/X11/app-defaults &&
	sudo make
}

build() {
	sudo make install
}

