#!/usr/bin/env bash
set -e

name=libxext
ver=1.3.6
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXext-1.3.6.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

