#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxext
ver=1.3.6
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXext-1.3.6.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

