#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libinput
ver=0.5.0
dependencies=(
libevdev
mtdev
)

make_dependencies=""
url=https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.27.1/libinput-1.27.1.tar.gz
prefix=$MANAGER_prefix/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release -D debug-gui=false -D tests=false -D libwacom=false -D udev-dir=/usr/lib/udev &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

