#!/usr/bin/env bash
set -e

name=libinput
ver=0.5.0
dependencies=(
libevdev
mtdev
)

make_dependencies=""
url=https://gitlab.freedesktop.org/libinput/libinput/-/archive/1.27.1/libinput-1.27.1.tar.gz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D debug-gui=false -D tests=false -D libwacom=false -D udev-dir=/usr/lib/udev &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

