#!/usr/bin/env bash
set -e

name=pango
ver=1.56.1
dependencies=(
freetype
fontconfig
harfbuzz
fribidi
glib
cairo
)

make_dependencies=""
url=https://download.gnome.org/sources/pango/1.56/pango-1.56.1.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release --wrap-mode=nofallback -D introspection=disabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

