#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=pango
ver=1.56.1
dependencies=(
freetype
fontconfig
harfbuzz
fribidi
glib
cairo
)

make_dependencies=""
url=https://download.gnome.org/sources/pango/1.56/pango-1.56.1.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release --wrap-mode=nofallback -D introspection=disabled &&
	sudo ninja
}

build() {
	sudo DESTDIR="$prefix" ninja install
}

