#!/usr/bin/env bash
set -e

name=xorgproto
ver=2024.1
dependencies=(
"util-macros"
)

make_dependencies=""
url=https://xorg.freedesktop.org/archive/individual/proto/xorgproto-2024.1.tar.xz

configure() {
	sudo meson setup build --prefix=/usr &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

