#!/usr/bin/env bash
set -e

name=niri
ver=v25.02
dependencies=(
rustc
)

make_dependencies=""
url=https://github.com/YaLTeR/niri/archive/refs/tags/v25.02.tar.gz

build() {
	sudo cargo build --no-default-features --features xdp-gnome-screencast --target-dir "$prefix"
}

