#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=niri
ver=v25.02
dependencies=(
rustc
)

make_dependencies=""
url=https://github.com/YaLTeR/niri/archive/refs/tags/v25.02.tar.gz
prefix=/var/xor/prefixes/$name

configure() {
	echo "Without configure"
}


build() {
	sudo cargo build --release --target-dir "$prefix"
}

