#!/usr/bin/env bash
set -e

name=font-util
ver=1.4.1
dependencies=()

url=https://www.x.org/archive//individual/font/font-util-1.4.1.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

