#!/usr/bin/env bash
set -e

name=rustup
ver=1.27.1
dependencies=(
rustc
)

make_dependencies=""
url=https://github.com/rust-lang/rustup/archive/refs/tags/1.27.1.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	echo "Without configure" 
}

build() {
	sudo cargo build --release --features no-self-update --bin rustup-init --target-dir="$prefix"
}

