#!/usr/bin/env bash
set -e

name=gsettings-desktop-schemas
ver=47.1
dependencies=(
	glib
	)

make_dependencies=""
url=https://download.gnome.org/sources/gsettings-desktop-schemas/47/gsettings-desktop-schemas-47.1.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}
