#!/usr/bin/env bash
set -e

name=rustc
ver=1.85.0
dependencies=(
llvm
)

make_dependencies=""
url=https://static.rust-lang.org/dist/rust-1.85.0-x86_64-unknown-linux-gnu.tar.xz

build() {
	sudo bash install.sh
}

after() {
	sudo ln -sf /usr/local/bin/rustc /usr/bin/rustc
	sudo ln -sf /usr/local/bin/rustfmt /usr/bin/rustfmt
	sudo ln -sf /usr/local/bin/rls /usr/bin/rls
	sudo ln -sf /usr/local/bin/rust-gdbgui /usr/bin/rust-gdbgui
	sudo ln -sf /usr/local/bin/rust-gdb /usr/bin/rust-gdb
	sudo ln -sf /usr/local/bin/rust-analyzer /usr/bin/rust-analyzer
	sudo ln -sf /usr/local/bin/cargo-clippy /usr/bin/cargo-clippy
	sudo ln -sf /usr/local/bin/rustdoc /usr/bin/rustdoc
	sudo ln -sf /usr/local/bin/rust-lldb /usr/bin/rust-lldb
	sudo ln -sf /usr/local/bin/clippy-driver /usr/bin/clippy-driver
	sudo ln -sf /usr/local/bin/cargo-fmt /usr/bin/cargo-fmt
	sudo ln -sf /usr/local/bin/cargo /usr/bin/cargo
}
