#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=tllist
ver=1.1.0
dependencies=()

make_dependencies=""
url=https://codeberg.org/dnkl/tllist/archive/1.1.0.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson --prefix=/usr --buildtype=release .. &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix"install
}

