#!/usr/bin/env bash
set -e

name=graphite2
ver=1.3.14
dependencies=(
cmake
)

make_dependencies=""
url=https://github.com/silnrsi/graphite/releases/download/1.3.14/graphite2-1.3.14.tgz

configure() {
	sudo cmake -D CMAKE_INSTALL_PREFIX=/usr . &&
	sudo make
}

build() {
	sudo make install
}

