#!/usr/bin/env bash
set -e

name=libfontenc
ver=1.1.8
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libfontenc-1.1.8.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

