#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=xkbutils
ver=1.0.6
dependencies=(
libxaw
)

make_dependencies=""
url=https://www.x.org/archive//individual/app/xkbutils-1.0.6.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

