#!/usr/bin/env bash
set -e

name=xkbutils
ver=1.0.6
dependencies=(
libxaw
)

make_dependencies=""
url=https://www.x.org/archive//individual/app/xkbutils-1.0.6.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

