#!/usr/bin/env bash
set -e

name=xauth
ver=1.1
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/app/xauth-1.1.tar.gz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

