#!/usr/bin/env bash
set -e

name=wayland
ver=1.23.0
dependencies=(
libxml2
)

make_dependencies=""
url=https://gitlab.freedesktop.org/wayland/wayland/-/releases/1.23.0/downloads/wayland-1.23.0.tar.xz

configure() {
	sudo meson setup build            \
	      --prefix=/usr       \
	      --buildtype=release \
	      -D documentation=false &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

