#!/usr/bin/env bash
set -e

name=libevdev
ver=1.2.2
dependencies=(
	python3
)

make_dependencies=""
url=https://www.freedesktop.org/software/libevdev/libevdev-1.13.3.tar.xz

configure() {
	sudo meson setup . --prefix=/usr --buildtype=release -D documentation=disabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

