#!/usr/bin/env bash
set -e

name=tmux
ver=3.5a
dependencies=(
libevent
cmake
)
#ncurses

make_dependencies=""
url=https://github.com/tmux/tmux/releases/download/3.5a/tmux-3.5a.tar.gz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

