#!/usr/bin/env bash
set -e

name=libdrm
ver=2.4.124
dependencies=()

make_dependencies=""
url=https://dri.freedesktop.org/libdrm/libdrm-2.4.124.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D udev=true -D valgrind=disabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

