#!/usr/bin/env bash
set -e

name=libxft
ver=2.3.8
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXft-2.3.8.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

