#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxft
ver=2.3.8
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXft-2.3.8.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

