#!/usr/bin/env bash
set -e

name=libuv
ver=1.50.0
dependencies=()

make_dependencies=""
url=https://dist.libuv.org/dist/v1.50.0/libuv-v1.50.0.tar.gz

configure() {
	sudo sh ./autogen.sh &&
	sudo ./configure --prefix=/usr --disable-static &&
	sudo make
}

build() {
	sudo make install
}

