#!/usr/bin/env bash
set -e

name=libxml2
ver=2.13.5
dependencies=()

make_dependencies=""
url=https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.5.tar.xz

configure() {

	#if [ ! -d "$prefix/etc" ]; then
	#	sudo mkdir -p $prefix/etc
	#fi

	sudo ./configure --prefix=/usr           \
            --sysconfdir=/etc       \
            --disable-static        \
            --with-history          \
            --with-icu              \
            PYTHON=/usr/bin/python3 &&
	sudo make
}

build() {
	sudo make install &&

	if [ -f "/usr/lib/libxml2.la" ]; then
		sudo rm -vf /usr/lib/libxml2.la
	fi

	if [ -f "/usr/bin/xml2-config" ]; then
		sudo sed '/libs=/s/xml2.*/xml2"/' -i /usr/bin/xml2-config
	fi
}

