#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=xf86-input-libinput
ver=1.5.0
dependencies=(
libinput
xorg-server
)

make_dependencies=""
url=https://www.x.org/pub/individual/driver/xf86-input-libinput-1.5.0.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install DESTDIR="$prefix"
}

