#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=fcft
ver=3.1.10
dependencies=(
fontconfig
freetype
pixman
tllist
)

make_dependencies=""
url=https://codeberg.org/dnkl/fcft/archive/3.1.10.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson --prefix=/usr --buildtype=release .. &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

