#!/usr/bin/env bash
set -e

name=libevent
ver=2.1.12-stable
dependencies=()

make_dependencies=""
url=https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz

configure() {
	sudo cmake -D CMAKE_INSTALL_PREFIX=/usr .
	sudo make

}

build() {
	sudo make install
}
