#!/usr/bin/env bash
set -e

name=pixman
ver=0.44.2
dependencies=()

make_dependencies=""
url=https://www.cairographics.org/releases/pixman-0.44.2.tar.gz

configure() {
	sudo meson setup --prefix=/usr --buildtype=release build &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

