#!/usr/bin/env bash
set -e

name=shared-mime-info
ver=2.4
dependencies=(
	glib
	libxml2
	)

make_dependencies=""
url=https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.4/shared-mime-info-2.4.tar.gz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D update-mimedb=true &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

