#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=shared-mime-info
ver=2.4
dependencies=(
	glib
	libxml2
	)

make_dependencies=""
url=https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.4/shared-mime-info-2.4.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release -D update-mimedb=true &&
	sudo ninja
}

build() {
	sudo DESTDIR="$prefix" ninja install
}

