#!/usr/bin/env bash
set -e

name=libxfixes
ver=6.0.1
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXfixes-6.0.1.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

