#!/usr/bin/env bash
set -e

name=libxdmcp
ver=1.1.5
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXdmcp-1.1.5.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

