#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxdmcp
ver=1.1.5
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXdmcp-1.1.5.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

