#!/usr/bin/env bash
set -e

name=libxshmfence
ver=1.3
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libxshmfence-1.3.tar.gz

configure() {
	sudo ./configure --prefix=/usr
	sudo make
}

build() {
	sudo make install
}

