#!/usr/bin/env bash
set -e

name=libxfont2
ver=2.0.7
dependencies=(
libfontenc
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXfont2-2.0.7.tar.xz

configure() {
	sudo ./configure --prefix=/usr --disable-devel-docs &&
	sudo make
}

build() {
	sudo make install
}

