#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxfont2
ver=2.0.7
dependencies=(
libfontenc
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXfont2-2.0.7.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr --disable-devel-docs &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

