#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=xkbcomp
ver=1.4.7
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/app/xkbcomp-1.4.7.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

