#!/usr/bin/env bash
set -e

name=xkbcomp
ver=1.4.7
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/app/xkbcomp-1.4.7.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

