#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=xcb-proto
ver=1.17.0
dependencies=()

make_dependencies=""
url=https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.17.0.tar.xz
prefix=/var/xor/prefixes/$name

configure() {
	sudo PYTHON=python3 ../configure --prefix=/usr
}

build() {
	sudo make DESTDIR="$prefix" install
}

