#!/usr/bin/env bash
set -e

name=xcb-proto
ver=1.17.0
dependencies=()

make_dependencies=""
url=https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.17.0.tar.xz

configure() {
	sudo PYTHON=python3 ./configure --prefix=/usr
}

build() {
	sudo make install
}

