#!/usr/bin/env bash
set -e

name=fontconfig
ver=2.16.0
dependencies=(
freetype
)

make_dependencies=""
url=https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.16.0.tar.xz

configure() {
	sudo ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-docs --docdir=/usr/share/doc/fontconfig-2.16.0 &&
	sudo make
}

build() {
	sudo make install
}
