#!/usr/bin/env bash
set -e

name=mtdev
ver=1.1.5
dependencies=()

make_dependencies=""
url=https://bitmath.org/code/mtdev/mtdev-1.1.5.tar.bz2

configure() {
	sudo ./configure --prefix=/usr --disable-static &&
	sudo make
}

build() {
	sudo make install
}

