#!/usr/bin/env bash
set -e

name=hwdata
ver=0.392
dependencies=()

make_dependencies=""
url=https://github.com/vcrhonek/hwdata/archive/v0.392/hwdata-0.392.tar.gz

configure() {
	sudo ./configure --prefix=/usr --disable-blacklist
}

build() {
	sudo make install
}

