#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=util-macros
ver=1.20.2
dependencies=()

make_dependencies=""
url=https://www.x.org/pub/individual/util/util-macros-1.20.2.tar.xz
prefix=/var/xor/prefixes/$name

configure() {
	sudo ../configure --prefix=/usr
}

build() {
	sudo make DESTDIR="$prefix" install
}

