#!/usr/bin/env bash
set -e

name=util-macros
ver=1.20.2
dependencies=()

make_dependencies=""
url=https://www.x.org/pub/individual/util/util-macros-1.20.2.tar.xz

configure() {
	sudo ./configure --prefix=/usr
}

build() {
	sudo make install
}

