#!/usr/bin/env bash
set -e

name=xkbcommon
ver=1.8.0
dependencies=(
xkeyboardconfig
libxcb
wayland
wayland-protocols
)

make_dependencies=""
url=https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-1.8.0/libxkbcommon-xkbcommon-1.8.0.tar.gz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D enable-docs=false &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

