#!/usr/bin/env bash
set -e

name=spirv-tools
ver=1.3.304.1
dependencies=(
cmake
spirv-headers
)

make_dependencies=""
url=https://github.com/KhronosGroup/SPIRV-Tools/archive/vulkan-sdk-1.4.304.1/SPIRV-Tools-vulkan-sdk-1.4.304.1.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo cmake -D CMAKE_INSTALL_prefix=/usr -D CMAKE_BUILD_TYPE=release -D SPIRV_WERROR=OFF -D BUILD_SHARED_LIBS=ON -D SPIRV_TOOLS_BUILD_STATIC=OOF -D SPIRV-Headers_SOURCE_DIR=/usr -G Ninja build &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

