#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=fuzzel
ver=1.11.1
dependencies=(
pixman
wayland
wayland-protocols
xkbcommon
tllist
scdoc
)

make_dependencies=""
url=https://codeberg.org/dnkl/fuzzel/archive/1.11.1.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson --prefix=/usr --buildtype=release -Denable-cairo=disabled -Dpng-backend=none -Dsvg-backend=none ..
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

