#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxrender
ver=0.9.12
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXrender-0.9.12.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

