#!/usr/bin/env bash
set -e

name=libxrender
ver=0.9.12
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXrender-0.9.12.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

