#!/usr/bin/env bash
set -e

name=libsm
ver=1.2.5
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libSM-1.2.5.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

