#!/usr/bin/env bash
set -e

name=libpng
ver=1.6.46
dependencies=()

make_dependencies=""
url=https://downloads.sourceforge.net/libpng/libpng-1.6.46.tar.xz

configure() {
	sudo ./configure --prefix=/usr --disable-static &&
	sudo make
}

build() {
	sudo make install
}
