#!/usr/bin/env bash
set -e

name=gtk3
ver=3.24.48
dependencies=(
	libepoxy
	pango
	at-spi2-core
	gdk-pixbuf
	)

make_dependencies=""
url=https://download.gnome.org/sources/gtk/3.24/gtk-3.24.48.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D man=false -D broadway_backend=true &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

