#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=gtk3
ver=3.24.48
dependencies=(
	libepoxy
	pango
	at-spi2-core
	gdk-pixbuf
	)

make_dependencies=""
url=https://download.gnome.org/sources/gtk/3.24/gtk-3.24.48.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release -D man=false -D broadway_backend=true &&
	sudo ninja
}

build() {
	sudo DESTDIR="$prefix" ninja install
}

