#!/usr/bin/env bash
set -e

name=xinit
ver=1.4.3
dependencies=()

make_dependencies=""
url=https://www.x.org/pub/individual/app/xinit-1.4.3.tar.xz

configure() {
	sudo ./configure --prefix=/usr --with-xinitdir=/etc/X11/app_defaults &&
	sudo make
}

build() {
	sudo make install
}
