#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=harfbuzz
ver=10.2.0
dependencies=()

make_dependencies=""
url=https://github.com/harfbuzz/harfbuzz/releases/download/10.2.0/harfbuzz-10.2.0.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --libdir=/usr/lib  --includedir=/usr/include --bindir=/usr/bin --datadir=/usr/share --prefix=/usr --buildtype=release -D graphite2=enabled &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

