#!/usr/bin/env bash
set -e

name=harfbuzz
ver=10.2.0
dependencies=(
	"graphite2"
	)

make_dependencies=""
url=https://github.com/harfbuzz/harfbuzz/releases/download/10.2.0/harfbuzz-10.2.0.tar.xz

configure() {
	sudo meson setup build --libdir=/usr/lib  --includedir=/usr/include --bindir=/usr/bin --datadir=/usr/share --prefix=/usr --buildtype=release -D graphite2=enabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

