#!/usr/bin/env bash
set -e

name=mesa
ver=24.3.4
dependencies=(
libdrm
mako
pyyaml
glslang
cbindgen
rust-bindgen
wayland
libx11
libxext
libxshmfence
libxxf86vm
libxrandr
libxfixes
)

make_dependencies=""
url=https://mesa.freedesktop.org/archive/mesa-24.3.4.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D platforms=x11,wayland -D gallium-drivers=radeonsi -D vulkan-drivers="" -D valgrind=disabled -D video-codecs=all -D libunwind=disabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

