#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=mesa
ver=24.3.4
dependencies=(
libdrm
mako
pyyaml
glslang
cbindgen
rust-bindgen
wayland
libx11
libxext
libxshmfence
libxxf86vm
libxrandr
libxfixes
)

make_dependencies=""
url=https://mesa.freedesktop.org/archive/mesa-24.3.4.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release -D platforms=x11,wayland -D gallium-drivers=radeonsi -D vulkan-drivers="" -D valgrind=disabled -D video-codecs=all -D libunwind=disabled &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

