#!/usr/bin/env bash
set -e

name=pyyaml
ver=6.0.2
dependencies=(
cython
libyaml
)
#pip3

make_dependencies=""
url=https://files.pythonhosted.org/packages/source/P/PyYAML/pyyaml-6.0.2.tar.gz

configure() {
	sudo pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
}

build() {
	sudo pip3 install --no-index --find-links dist --no-user PyYAML
}

