#!/usr/bin/env bash
set -e

name=libepoxy
ver=1.5.10
dependencies=(
mesa
)

make_dependencies=""
url=https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.10.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}
