#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libepoxy
ver=1.5.10
dependencies=(
mesa
)

make_dependencies=""
url=https://download.gnome.org/sources/libepoxy/1.5/libepoxy-1.5.10.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}
