#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxmu
ver=1.2.1
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXmu-1.2.1.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

