#!/usr/bin/env bash
set -e

name=libxmu
ver=1.2.1
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXmu-1.2.1.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

