#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=glslang
ver=15.1.0
dependencies=(
cmake
spirv-tools
)

make_dependencies=""
url=https://github.com/KhronosGroup/glslang/archive/15.1.0/glslang-15.1.0.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo cmake -D CMAKE_INSTALL_prefix=/usr -D CMAKE_BUILD_TYPE=Release -D ALLOW_EXTERNAL_SPIRV_TOOLS=ON -D BUILD_SHARED_LIBS=ON -D GLSLANG_TESTS=ON -G Ninja .. &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

