#!/usr/bin/env bash
set -e

name=libxau
ver=1.0.12
dependencies=(
xorgproto
)

make_dependencies=""
url=https://www.x.org/pub/individual/lib/libXau-1.0.12.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

