#!/usr/bin/env bash
set -e

name=scdoc
ver=1.11.3
dependencies=()

make_dependencies=""
url=https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.3.tar.gz

configure() {
	sudo make prefix=/usr
}

build() {
	sudo make install
}

