#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=scdoc
ver=1.11.3
dependencies=()

make_dependencies=""
url=https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.3.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	pushd ..
		sudo make prefix=/usr
	popd
}

build() {
	pushd ..
		sudo make DESTDIR="$prefix" install
	popd
}

