#!/usr/bin/env bash
set -e

name=libxi
ver=1.8
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXi-1.8.tar.gz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}
