#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxi
ver=1.8
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXi-1.8.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}
