#!/usr/bin/env bash
set -e

name=libxxf86vm
ver=1.1.6
dependencies=(
	
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXxf86vm-1.1.6.tar.xz

configure() {
	sudo ./configure --prefix=/usr
	sudo make
}

build() {
	sudo make install
}

