#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxkbfile
ver=1.1.3
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libxkbfile-1.1.3.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

