#!/usr/bin/env bash
set -e

name=libxkbfile
ver=1.1.3
dependencies=(
	"libx11"
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libxkbfile-1.1.3.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

