#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libx11
ver=1.8
dependencies=(
xorgproto
xtrans
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libX11-1.8.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}
