#!/usr/bin/env bash
set -e

name=libx11
ver=1.8
dependencies=(
xorgproto
xtrans
libxcb
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libX11-1.8.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}
