#!/usr/bin/env bash
set -e

name=xorg-server
ver=21.1.13

dependencies=(
libxcvt
pixman
libxkbfile
libxfont2
font-util
libxdmcp
xkeyboardconfig
libtirpc
libepoxy
libpciaccess
xorgproto
libdrm
libinput
)
#xorg-Fonts
#xorg-libinput

url=https://www.x.org/pub/individual/xserver/xorg-server-21.1.13.tar.xz

configure(){

        sudo meson setup build               \
              --prefix=/usr  \
              --localstatedir=/var   \
              --sysconfdir=/usr   \
              -D glamor=true         \
              -D systemd_logind=true \
              -D xkb_output_dir=/var/lib/xkb &&

        sudo ninja -C build
}

build(){
        sudo ninja install -C build
}
