#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libxrandr
ver=1.5.4
dependencies=(
libxrender
libxext
)

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXrandr-1.5.4.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

