#!/usr/bin/env bash
set -e

name=libxpm
ver=3.5.17
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXpm-3.5.17.tar.xz

configure() {
	sudo ./configure --prefix=/usr --disable-open-zfile &&
	sudo make
}

build() {
	sudo make install
}

