#!/usr/bin/env bash
set -e

name=cmake
ver=3.31.5
dependencies=(
libarchive
libuv
)

make_dependencies=""
url=https://cmake.org/files/v3.31/cmake-3.31.5.tar.gz

configure() {

	sudo sed -i '/"lib64"/s/64//' ./Modules/GNUInstallDirs.cmake &&

	sudo ./bootstrap --prefix=/usr        \
		    --system-libs        \
		    --no-system-jsoncpp  \
		    --no-system-cppdap   \
		    --no-system-librhash &&
	sudo make
}

build() {
	sudo make install
}

