#!/usr/bin/env bash
set -e

name=mako
ver=1.3.9
dependencies=(
)
#pip3

make_dependencies=""
url=https://files.pythonhosted.org/packages/source/M/Mako/mako-1.3.9.tar.gz

configure() {
	sudo pip3 wheel -w dist --no-build-isolation --no-deps --no-cache-dir $PWD
}

build() {
	sudo pip3 install --no-index --find-links dist --no-user Mako
}
