#!/usr/bin/env bash
set -e

name=xkeyboardconfig
ver=2.44
dependencies=()

make_dependencies=""
url=https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-2.44.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

