#!/usr/bin/env bash
set -e

name=gobject-introspection
ver=1.82.0
dependencies=(
glib
)

make_dependencies=""
url=https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-1.82.0.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

