#!/usr/bin/env bash
set -e

name=libxcursor
ver=1.2.3
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libXcursor-1.2.3.tar.xz

configure() {
	sudo ./configure --prefix=/usr --sysconfdir=/etc --disable-static &&
	sudo make
}

build() {
	sudo make install
}

