#!/usr/bin/env bash
set -e

name=glib
ver=2.82.4
dependencies=(
docutils
)

make_dependencies=""
url=https://download.gnome.org/sources/glib/2.82/glib-2.82.4.tar.xz

configure() {
	sudo meson setup build \
		--prefix=/usr \
		--buildtype=release \
		-D introspection=enabled \
		-D glib_debug=disabled \
		-D man-pages=enabled \
		-D sysprof=disabled &&

	sudo ninja -C build
}

build() {
	sudo ninja install -C build

	#cd build &&

	#export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH

	#sudo wget https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-1.82.0.tar.xz &&
	#sudo tar xf gobject-introspection-1.82.0.tar.xz &&

	#pushd gobject-introspection-1.82.0
	#	find
	#	sudo meson setup gi-build \
	#	    --prefix=/usr --buildtype=release     &&
	#	sudo ninja -C gi-build

	#	ninja -C gi-build test

	#	sudo ninja -C gi-build install
	#popd

	#cd ..

	#sudo meson configure -D introspection=enabled &&
	#sudo ninja

	#sudo ninja install
}
