#!/usr/bin/env bash
set -e

name=glib
ver=2.82.4
dependencies=(
docutils
)

make_dependencies=""
url=https://download.gnome.org/sources/glib/2.82/glib-2.82.4.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release -D introspection=enabled -D glib_debug=disabled -D man-pages=enabled -D sysprof=disabled &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build

	#pushd ..
	#	sudo wget https://download.gnome.org/sources/gobject-introspection/1.82/gobject-introspection-1.82.0.tar.xz
	#	sudo tar xf gobject-introspection-1.82.0.tar.xz &&

	#	sudo meson setup gobject-introspection-1.82.0 gi-build --prefix=/usr --buildtype=release &&
	#	sudo ninja -C gi-build &&
	#	sudo DESTDIR="$prefix" ninja -C gi-build install
	#popd

		#echo $(pwd)
		#sudo meson configure -D introspection=enabled &&
		#sudo ninja
		#sudo DESTDIR="$prefix" ninja install
}
