#!/usr/bin/env bash
set -e

name=xtrans
ver=1.5.2
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/xtrans-1.5.2.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

