#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=xtrans
ver=1.5.2
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/xtrans-1.5.2.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo ../configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

