#!/usr/bin/env bash
set -e

name=xf86-input-evdev
ver=2.11.0
dependencies=(
	libevdev
	mtdev
	)

make_dependencies=""
url=https://www.x.org/pub/individual/driver/xf86-input-evdev-2.11.0.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

