#!/usr/bin/env bash
set -e

name=cbindgen
ver=0.28.0
dependencies=(
rustc
)

make_dependencies=""
url=https://github.com/mozilla/cbindgen/archive/v0.28.0/cbindgen-0.28.0.tar.gz

build() {
	sudo cargo build --release
}

after() {
	sudo install -Dm755 target/release/cbindgen /usr/bin
}
