#!/usr/bin/env bash
set -e

name=libyaml
ver=0.2.5
dependencies=()

make_dependencies=""
url=https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz

configure() {
	sudo ./configure --prefix=/usr --disable-static &&
	sudo make
}

build() {
	sudo make install
}

