#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libyaml
ver=0.2.5
dependencies=()

make_dependencies=""
url=https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo ../configure --prefix=/usr --disable-static &&
	sudo make
}

build() {
	sudo make DESTDIR="$prefix" install
}

