#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libpciaccess
ver=0.18
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libpciaccess-0.18.tar.xz
prefix=$MANAGER_prefix/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

