#!/usr/bin/env bash
set -e

name=libpciaccess
ver=0.18
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libpciaccess-0.18.tar.xz

configure() {
	sudo meson setup build --prefix=/usr --buildtype=release &&
	sudo ninja -C build
}

build() {
	sudo ninja install -C build
}

