#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=libdisplay-info
ver=0.2.0
dependencies=(
hwdata
)

make_dependencies=""
url=https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/0.2.0/downloads/libdisplay-info-0.2.0.tar.xz
prefix=$MANAGER_PREFIX/$name

configure() {
	sudo meson setup .. --prefix=/usr --buildtype=release &&
	sudo ninja
}

build() {
	sudo ninja DESTDIR="$prefix" install
}

