#!/usr/bin/env bash
set -e

name=libice
ver=1.1.2
dependencies=()

make_dependencies=""
url=https://www.x.org/archive//individual/lib/libICE-1.1.2.tar.xz

configure() {
	sudo ./configure --prefix=/usr &&
	sudo make
}

build() {
	sudo make install
}

