#!/usr/bin/env bash
set -e

source $(dirname "$0")/../core/config.sh

name=rust-bindgen
ver=0.71.1
dependencies=(
rustc
llvm
)

make_dependencies=""
url=https://github.com/rust-lang/rust-bindgen/archive/v0.71.1/rust-bindgen-0.71.1.tar.gz
prefix=$MANAGER_PREFIX/$name

configure() {
	echo "Without config file"
}

build() {
	pushd ..
		sudo cargo build --release --target-dir "$prefix"
	popd

	#TODO: Need to add the bash/zsh completion
}

