#!/usr/bin/env bash
set -e

name=rust-bindgen
ver=0.71.1
dependencies=(
rustc
llvm
)

make_dependencies=""
url=https://github.com/rust-lang/rust-bindgen/archive/v0.71.1/rust-bindgen-0.71.1.tar.gz

build() {
	sudo cargo build --release

	#TODO: Need to add the bash/zsh completion
}

